### ISSUE TITLE
Not all threads in ThreadPoolExecutor can be scheduled when using AsyncTask.

### ISSUE THREAD

**Issue by MissiontoMars** [Himmele/My-Blog-Repository#1]
I have a problem when using AsyncTask as a thread-pool. Not all threads in ThreadPoolExecutor can be scheduled.

As in AsyncTaskExample.cpp,  if we create lots of ExampleAsyncTask in onLooperReady：

		mHandler = new Handler();

		// AsyncTasks must be executed by a Looper thread because of the callback message handling
		//ExampleAsyncTask* asyncTask1 = new ExampleAsyncTask();
		//asyncTask1->execute(1234567);

		int count=10;
		while(count--) {
			ExampleAsyncTask* asyncTask2 = new ExampleAsyncTask();
			asyncTask2->executeOnExecutor(AsyncTaskBase::THREAD_POOL_EXECUTOR, 123);
		}

		mHandler->postDelayed(newRunnable(*this, &AsyncTaskSupervisor::shutdownLooper), 20000);

The execution result is:
# ./AsyncTaskExample
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onPreExecute on thread -1225719468
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::doInBackground on thread -1196129400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225719468 with value 61
ExampleAsyncTask::onPostExecute on thread -1225719468 with result 123

So, we can find that only one thread(-1196129400) has been scheduled.

After a little bit  work, i find that the pthread_cond_wait has not been wrappered with pthread_mutex_lock and pthread_mutex_unlock:

		void CondVar::wait() { pthread_cond_wait(&mCondVar, &mCondVarLock.mMutex); }

should be:

		void CondVar::wait() {
			mCondVarLock.lock();
			pthread_cond_wait(&mCondVar, &mCondVarLock.mMutex); 
			mCondVarLock.unlock();
		}

Then, the execution result is:

# ./AsyncTaskExample
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::doInBackground on thread -1214217984 with param 123
ExampleAsyncTask::doInBackground on thread -1214217400 with param 123
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::doInBackground on thread -1214216816 with param 123
ExampleAsyncTask::doInBackground on thread -1214216232 with param 123
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onPreExecute on thread -1225637548
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::doInBackground on thread -1214217984 with param 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::doInBackground on thread -1214217400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::doInBackground on thread -1214216232 with param 123
ExampleAsyncTask::doInBackground on thread -1214216816 with param 123
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::doInBackground on thread -1214217984 with param 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::doInBackground on thread -1214217400 with param 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onProgressUpdate on thread -1225637548 with value 61
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123
ExampleAsyncTask::onPostExecute on thread -1225637548 with result 123

Tasks  were assigned to all threads(4).

In addition, i comment out the:

		//SerialExecutor AsyncTaskBase::SERIAL_EXECUTOR

in AsyncTask.cpp, otherwise the execution will be blocked. It doesn’t matter.

**Comment by Himmele** [comment]
AsyncTask.execute runs the AsyncTask on the serial executor by default. You have to use AsyncTask.executeOnExecutor with the AsyncTask.THREAD_POOL_EXECUTOR to run them in parallel.

**Comment by Himmele** [comment]
See also https://github.com/Himmele/Mindroid.cpp.git for the latest version of Mindroid. Himmele/My-Blog-Repository contains a pretty old version of this stuff.

**Comment by MissiontoMars** [comment]
@Himmele I test it using AsyncTask.executeOnExecutor, not AsyncTask.execute. Has this problem been solved in latest version of Mindroid?

**Comment by MissiontoMars** [comment]
@Himmele after grep "pthread_cond_wait" in latest version of Mindroid, pthread_cond_wait has not been wrappered with pthread_mutex_lock and pthread_mutex_unlock. so i guess this problem may still exists in latest version. Threads blocked on the condition variable can not be waked up.

**Comment by Himmele** [comment]
The thing is that the API is used differently so that lock and unlock calls are not done in Condition::await but in the surrounding context. Just take a look e.g. at MessageQueue.cpp. There you see that the locking/unlocking is done in the surrounding code. Maybe I should add an assert to Condition::await to make it more clear how to use the API.

**Comment by MissiontoMars** [comment]
Yeah, I see. The latest version should work normally. As for the old version, there is really something wrong, i will fix it by myself.

**Comment by Himmele** [comment]
I added better CondVar failure assertions and logging now to Mindroid.cpp. See https://github.com/Himmele/Mindroid.cpp/commit/79b5504314c2f0beb24fe80c60c902c9b23c3172
